GET http://localhost:3000/api/v0/bikes
###

GET http://localhost:3000/api/v0/bikes/3
###

DELETE http://localhost:3000/api/v0/bikes/3
###

POST http://localhost:3000/api/v0/bikes
Content-Type: application/json; charset=utf-8

{"brand": "Yamaha", "price": 7000}
###

PATCH http://localhost:3000/api/v0/bikes/3
Content-Type: application/json; charset=utf-8

{"brand": "Ducati", "price": 9000}
###
